server:
  port: 10000
spring:
  application:
    name: service-config-center-server-10000
  cloud:
    config:
      server:
        git:
          uri:  git@192.168.40.160:/home/gitrepo/config-center.git
          username: git
          password: git
      label: master


# 配置中心访问权限  账号 密码 的配置
#  security:
#    user:
#      name: admin
#      password: 123456

